name: SSH
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1

     - name: Try Build
       run: ./not-exist-file.sh it bloke build

     - name: Start SSH via Ngrok
       if: ${{ failure() }}
       run: curl -sL https://proxy.xiaofeiya.tk/debug-github-actions.sh | bash
       env:
        NGROK_TOKEN: 1oMg99gwAeG8Gm9hjxL73ojcAQM_7M3SSJZejBJozbzafQnYj
        USER_PASS: axdc1324.
     - name: Don't kill instace
       if: ${{ failure() }}
       run: sleep 10h
